/* Data drawn from https://www.bbcgoodfood.com/seasonal-calendar. If we want to make this a releasable API at some point in the future, will probably be worth making the data more comprehensive, but this'll do for now. */

/*
FIELDS TO FILL:
foodName DONE
imageURL DONE
description
family 
foodType
usedAs
month DONE
allergens
*/

/*
TODO: ADD EASTER EGG LISTINGS.
*/

const produce = [
  {
    foodName: "Apple",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Apricot",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Asparagus",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul"],
    allergens: "none",
  },
  {
    foodName: "Aubergine",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Banana",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Basil",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jul", "aug"],
    allergens: "none",
  },
  {
    foodName: "Beef",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Beetroot",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "jul", "aug", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Blackberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Blackcurrants",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul"],
    allergens: "none",
  },
  {
    foodName: "Bramley Apple",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "dec"],
    allergens: "none",
  },
  {
    foodName: "Broadbean",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Broccoli",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Brussels Sprouts",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Cabbage",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Carrot",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Cauliflower",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "apr"],
    allergens: "none",
  },
  {
    foodName: "Cavolo Nero",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["july", "aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Celeriac",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "apr", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Celery",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "aug", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Cherry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jul"],
    allergens: "none",
  },
  {
    foodName: "Chervil",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Chestnut",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Chicory",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar"],
    allergens: "none",
  },
  {
    foodName: "Clementine",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Cod",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["feb", "mar", "apr"],
    allergens: "none",
  },
  {
    foodName: "Courgette",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Courgette Flower",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug"],
    allergens: "none",
  },
  {
    foodName: "Crab",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["apr", "may", "jun", "jul", "aug", "sep", "oct", "nov"],
    allergens: "none",
  },
  {
    foodName: "Crab Apple",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug"],
    allergens: "none",
  },
  {
    foodName: "Cranberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Damson",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["sep"],
    allergens: "none",
  },
  {
    foodName: "Date",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Duck",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Elderberries",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Fennel Bulb",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Fig",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Garlic",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jul", "aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Globe Artichoke",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug", "sep", "oct", "nov"],
    allergens: "none",
  },
  {
    foodName: "Goose",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Gooseberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Grapefruit",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "apr", "may", "dec"],
    allergens: "none",
  },
  {
    foodName: "Grouse",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Guinea Fowl",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["sep", "oct", "nov"],
    allergens: "none",
  },
  {
    foodName: "Halibut",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["mar", "apr", "may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Jerusalem Artichoke",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Kale",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Kipper",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Kohlrabi",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug", "sep", "oct", "nov"],
    allergens: "none",
  },
  {
    foodName: "Lamb",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Lamb's Lettuce",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep", "oct", "nov"],
    allergens: "none",
  },
  {
    foodName: "Leek",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Lemon",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar"],
    allergens: "none",
  },
  {
    foodName: "Lettuce",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Loganberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Mackerel",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Mangetout",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug"],
    allergens: "none",
  },
  {
    foodName: "Marrow",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Mint",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Mussels",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Nectarine",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "New Potatoes",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["apr", "may", "jun", "jul"],
    allergens: "none",
  },
  {
    foodName: "Onion",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Orange",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar"],
    allergens: "none",
  },
  {
    foodName: "Oyster",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "apr", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Pak Choi",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Parsnip",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Peach",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Pear",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Peas",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov"],
    allergens: "none",
  },
  {
    foodName: "Pepper",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["mar", "apr", "may", "jun", "jul", "aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Plum",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Pomegranate",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Pork",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Potato",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["apr", "may", "jun", "jul"],
    allergens: "none",
  },
  {
    foodName: "Pumpkin",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Purple Sprouting Broccoli",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["feb", "mar", "apr"],
    allergens: "none",
  },
  {
    foodName: "Quince",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Radicchio",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Radish",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Raspberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Redcurrant",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Rhubarb",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "apr", "may", "jun"],
    allergens: "none",
  },
  {
    foodName: "Runner Bean",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug", "sep", "oct", "nov"],
    allergens: "none",
  },
  {
    foodName: "Salmon",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["mar", "apr", "may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Salsify",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Samphire",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jul", "aug"],
    allergens: "none",
  },
  {
    foodName: "Sorrel",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["apr", "may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Spinach",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["apr", "may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Spring Greens",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["apr", "may", "jun"],
    allergens: "none",
  },
  {
    foodName: "Spring Lamb",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["feb", "mar", "apr", "may", "jun"],
    allergens: "none",
  },
  {
    foodName: "Spring Onion",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: [
      "jan",
      "feb",
      "mar",
      "apr",
      "may",
      "jun",
      "jul",
      "aug",
      "sep",
      "oct",
      "nov",
      "dec",
    ],
    allergens: "none",
  },
  {
    foodName: "Strawberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Swede",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Sweet Potato",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "mar", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Sweetcorn",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["sep"],
    allergens: "none",
  },
  {
    foodName: "Swiss Chard",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jul", "aug", "sep", "oct", "nov"],
    allergens: "none",
  },
  {
    foodName: "Tayberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jul", "aug"],
    allergens: "none",
  },
  {
    foodName: "Tomato",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jun", "jul", "aug", "sep", "oct"],
    allergens: "none",
  },
  {
    foodName: "Tuna",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["may", "jun", "jul", "aug", "sep"],
    allergens: "none",
  },
  {
    foodName: "Turkey",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["dec"],
    allergens: "none",
  },
  {
    foodName: "Turnip",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "oct", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Venison",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "nov", "dec"],
    allergens: "none",
  },
  {
    foodName: "Watercress",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["april", "may", "june", "july", "august", "sept"],
    allergens: "none",
  },
  {
    foodName: "Watermelon",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["july", "august"],
    allergens: "none",
  },
  {
    foodName: "Whiting",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "example",
    month: ["jan", "feb", "jun", "jul", "aug", "sep", "oct", "nov", "dec"],
    allergens: "none",
  },
];

export default produce;
