/* Data drawn from https://www.bbcgoodfood.com/seasonal-calendar. If we want to make this a releasable API at some point in the future, will probably be worth making the data more comprehensive, but this'll do for now. */

/*
FIELDS TO FILL:
foodName DONE
imageURL DONE
description
family 
foodType DONE WITH CAVEAT THIS WAS A NIGHTMARE
usedAs DONE
month DONE
allergens DONE WITH CAVEAT THAT I DON'T KNOW ALL ALLERGENS, WILL WANT DOUBLE-CHECKING
*/

/*
TODO: ADD EASTER EGG LISTINGS.
*/

const produce = [
  {
    foodName: "Apple",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "Rosaceae",
    foodType: "Pome",
    usedAs: "Fruit",
    month: ["Jan", "Feb", "Sep", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Apricot",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Drupe",
    usedAs: "Fruit",
    month: ["May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Asparagus",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Stem",
    usedAs: "Vegetable",
    month: ["Jun", "Jul"],
    allergens: "NA",
  },
  {
    foodName: "Aubergine",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Vegetable",
    month: ["Jun", "Jul", "Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Banana",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Basil",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Herb",
    usedAs: "Herb",
    month: ["Jul", "Aug"],
    allergens: "NA",
  },
  {
    foodName: "Beef",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Meat",
    usedAs: "Meat",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Beetroot",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jan", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Blackberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Blackcurrants",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Jun", "Jul"],
    allergens: "NA",
  },
  {
    foodName: "Bramley Apple",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Pome",
    usedAs: "Fruit",
    month: ["Jan", "Feb", "Mar", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Broadbean",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Legume",
    usedAs: "Vegetable",
    month: ["Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Broccoli",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Cruciferous",
    usedAs: "Vegetable",
    month: ["Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Brussels Sprouts",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Mar", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Cabbage",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Carrot",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Cauliflower",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Cruciferous",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Mar", "Apr"],
    allergens: "NA",
  },
  {
    foodName: "Cavolo Nero",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Cruciferous",
    usedAs: "Vegetable",
    month: ["Jul", "Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Celeriac",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Mar", "Apr", "Sep", "Oct", "Nov", "Dec"],
    allergens: "Celery",
  },
  {
    foodName: "Celery",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Stem",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Aug", "Sep", "Oct", "Nov", "Dec"],
    allergens: "Celery",
  },
  {
    foodName: "Cherry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Jul"],
    allergens: "NA",
  },
  {
    foodName: "Chervil",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Herb",
    usedAs: "Herb",
    month: ["May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Chestnut",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Nut",
    usedAs: "Nut",
    month: ["Jan", "Oct", "Nov", "Dec"],
    allergens: "Nut",
  },
  {
    foodName: "Chicory",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Mar"],
    allergens: "NA",
  },
  {
    foodName: "Clementine",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Citrus",
    usedAs: "Fruit",
    month: ["Jan", "Feb", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Cod",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fish",
    usedAs: "Fish",
    month: ["Feb", "Mar", "Apr"],
    allergens: "Fish",
  },
  {
    foodName: "Courgette",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Squash",
    usedAs: "Vegetable",
    month: ["Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Courgette Flower",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Squash",
    usedAs: "Vegetable",
    month: ["Jun", "Jul", "Aug"],
    allergens: "NA",
  },
  {
    foodName: "Crab",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "example",
    usedAs: "Fish",
    month: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov"],
    allergens: "Crustacean",
  },
  {
    foodName: "Crab Apple",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Pome",
    usedAs: "Fruit",
    month: ["Aug"],
    allergens: "NA",
  },
  {
    foodName: "Cranberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Damson",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Drupe",
    usedAs: "Fruit",
    month: ["Sep"],
    allergens: "NA",
  },
  {
    foodName: "Date",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Jan", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Duck",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fowl",
    usedAs: "Meat",
    month: ["Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Elderberries",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Fennel Bulb",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Stem",
    usedAs: "Vegetable",
    month: ["Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Fig",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Garlic",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Herb",
    usedAs: "Herb",
    month: ["Jul", "Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Globe Artichoke",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jun", "Jul", "Aug", "Sep", "Oct", "Nov"],
    allergens: "NA",
  },
  {
    foodName: "Goose",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fowl",
    usedAs: "Meat",
    month: ["Jan", "Sep", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Gooseberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Grapefruit",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Citrus",
    usedAs: "Fruit",
    month: ["Jan", "Feb", "Mar", "Apr", "May", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Grouse",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fowl",
    usedAs: "Meat",
    month: ["Aug", "Sep", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Guinea Fowl",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fowl",
    usedAs: "Meat",
    month: ["Sep", "Oct", "Nov"],
    allergens: "NA",
  },
  {
    foodName: "Halibut",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fish",
    usedAs: "Fish",
    month: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "Fish",
  },
  {
    foodName: "Jerusalem Artichoke",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Mar", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Kale",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Cruciferous",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Kipper",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fish",
    usedAs: "Fish",
    month: ["May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "Fish",
  },
  {
    foodName: "Kohlrabi",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Aug", "Sep", "Oct", "Nov"],
    allergens: "NA",
  },
  {
    foodName: "Lamb",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Meat",
    usedAs: "Meat",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Lamb's Lettuce",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov"],
    allergens: "NA",
  },
  {
    foodName: "Leek",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Mar", "Sep", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Lemon",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Citrus",
    usedAs: "Fruit",
    month: ["Jan", "Feb", "Mar"],
    allergens: "NA",
  },
  {
    foodName: "Lettuce",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Loganberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Mackerel",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fish",
    usedAs: "Fish",
    month: ["May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    allergens: "Fish",
  },
  {
    foodName: "Mangetout",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Legume",
    usedAs: "Vegetable",
    month: ["Jun", "Jul", "Aug"],
    allergens: "NA",
  },
  {
    foodName: "Marrow",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Squash",
    usedAs: "Vegetable",
    month: ["Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Mint",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Herb",
    usedAs: "Herb",
    month: ["May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Mussels",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fish",
    usedAs: "Fish",
    month: ["Jan", "Feb", "Mar", "Oct", "Nov", "Dec"],
    allergens: "Crustacean",
  },
  {
    foodName: "Nectarine",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Citrus",
    usedAs: "Fruit",
    month: ["May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "New Potatoes",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Apr", "May", "Jun", "Jul"],
    allergens: "NA",
  },
  {
    foodName: "Onion",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Allium",
    usedAs: "Vegetable",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Orange",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Citrus",
    usedAs: "Fruit",
    month: ["Jan", "Feb", "Mar"],
    allergens: "NA",
  },
  {
    foodName: "Oyster",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fish",
    usedAs: "Fish",
    month: ["Jan", "Feb", "Mar", "Apr", "Sep", "Oct", "Nov", "Dec"],
    allergens: "Crustacean",
  },
  {
    foodName: "Pak Choi",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Parsnip",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Mar", "Sep", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Peach",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Drupe",
    usedAs: "Fruit",
    month: ["Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Pear",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Pome",
    usedAs: "Fruit",
    month: ["Jan", "Sep", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Peas",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Legume",
    usedAs: "Vegetable",
    month: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov"],
    allergens: "NA",
  },
  {
    foodName: "Pepper",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Vegetable",
    month: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Plum",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Drupe",
    usedAs: "Fruit",
    month: ["Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Pomegranate",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Pork",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Meat",
    usedAs: "Meat",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Potato",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Apr", "May", "Jun", "Jul"],
    allergens: "NA",
  },
  {
    foodName: "Pumpkin",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Squash",
    usedAs: "Vegetable",
    month: ["Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Purple Sprouting Broccoli",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Cruciferous",
    usedAs: "Vegetable",
    month: ["Feb", "Mar", "Apr"],
    allergens: "NA",
  },
  {
    foodName: "Quince",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Pome",
    usedAs: "Fruit",
    month: ["Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Radicchio",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Radish",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Raspberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Redcurrant",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Rhubarb",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Stem",
    usedAs: "Fruit",
    month: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    allergens: "NA",
  },
  {
    foodName: "Runner Bean",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Legume",
    usedAs: "Vegetable",
    month: ["Jun", "Jul", "Aug", "Sep", "Oct", "Nov"],
    allergens: "NA",
  },
  {
    foodName: "Salmon",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fish",
    usedAs: "Fish",
    month: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Fep"],
    allergens: "Fish",
  },
  {
    foodName: "Salsify",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jan", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Samphire",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["Jul", "Aug"],
    allergens: "NA",
  },
  {
    foodName: "Sorrel",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Spinach",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Spring Greens",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["Apr", "May", "Jun"],
    allergens: "NA",
  },
  {
    foodName: "Spring Lamb",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Meat",
    usedAs: "Meat",
    month: ["Feb", "Mar", "Apr", "May", "Jun"],
    allergens: "NA",
  },
  {
    foodName: "Spring Onion",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Allium",
    usedAs: "Vegetable",
    month: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    allergens: "NA",
  },
  {
    foodName: "Strawberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Swede",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Sweet Potato",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Mar", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Sweetcorn",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Scientific Anomaly",
    usedAs: "Vegetable",
    month: ["Sep"],
    allergens: "NA",
  },
  {
    foodName: "Swiss Chard",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["Jul", "Aug", "Sep", "Oct", "Nov"],
    allergens: "NA",
  },
  {
    foodName: "Tayberry",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Jul", "Aug"],
    allergens: "NA",
  },
  {
    foodName: "Tomato",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Vegetable",
    month: ["Jun", "Jul", "Aug", "Sep", "Oct"],
    allergens: "NA",
  },
  {
    foodName: "Tuna",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fish",
    usedAs: "Fish",
    month: ["May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "Fish",
  },
  {
    foodName: "Turkey",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fowl",
    usedAs: "Meat",
    month: ["Dec"],
    allergens: "NA",
  },
  {
    foodName: "Turnip",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Root",
    usedAs: "Vegetable",
    month: ["Jan", "Feb", "Oct", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Venison",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Meat",
    usedAs: "Meat",
    month: ["Jan", "Feb", "Nov", "Dec"],
    allergens: "NA",
  },
  {
    foodName: "Watercress",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Leaf",
    usedAs: "Vegetable",
    month: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    allergens: "NA",
  },
  {
    foodName: "Watermelon",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Berry",
    usedAs: "Fruit",
    month: ["Jul", "Aug"],
    allergens: "NA",
  },
  {
    foodName: "Whiting",
    imageURL: "https://via.placeholder.com/200x200",
    description:
      "This is an example entry, and this is an example description.",
    family: "example",
    foodType: "Fish",
    usedAs: "Fish",
    month: ["Jan", "Feb", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    allergens: "Fish",
  },
];

export default produce;
